# Base de datos
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.highlight_sql=false

# JWT
motorbit.jwt.secret=${JWT_SECRET}

# Logging
logging.level.root=INFO
logging.level.com.motorbit=INFO

# Evitar SQL detallado en producción
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=OFF