# Base de datos
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${POSTGRES_DB:motorbit}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin123}

# Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# JWT
motorbit.jwt.secret=${JWT_SECRET:mi-clave-super-secreta-para-jwt-token-generation-2026}

# Logging
logging.level.root=INFO
logging.level.com.motorbit=DEBUG

# SQL de Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE